#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libusb-compat
Version  : 0.1.7
Release  : 7
URL      : https://github.com/libusb/libusb-compat-0.1/releases/download/v0.1.7/libusb-compat-0.1.7.tar.bz2
Source0  : https://github.com/libusb/libusb-compat-0.1/releases/download/v0.1.7/libusb-compat-0.1.7.tar.bz2
Summary  : USB access library (libusb-1.0 compat wrapper)
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: libusb-compat-lib = %{version}-%{release}
Requires: libusb-compat-license = %{version}-%{release}
BuildRequires : pkgconfig(libusb-1.0)

%description
libusb-compat-0.1
=================
A compatibility layer allowing applications written for libusb-0.1 to work
with libusb-1.0. libusb-compat-0.1 attempts to look, feel, smell and walk
like libusb-0.1.

%package dev
Summary: dev components for the libusb-compat package.
Group: Development
Requires: libusb-compat-lib = %{version}-%{release}
Provides: libusb-compat-devel = %{version}-%{release}
Requires: libusb-compat = %{version}-%{release}

%description dev
dev components for the libusb-compat package.


%package lib
Summary: lib components for the libusb-compat package.
Group: Libraries
Requires: libusb-compat-license = %{version}-%{release}

%description lib
lib components for the libusb-compat package.


%package license
Summary: license components for the libusb-compat package.
Group: Default

%description license
license components for the libusb-compat package.


%prep
%setup -q -n libusb-compat-0.1.7
cd %{_builddir}/libusb-compat-0.1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1616194436
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1616194436
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libusb-compat
cp %{_builddir}/libusb-compat-0.1.7/COPYING %{buildroot}/usr/share/package-licenses/libusb-compat/caeb68c46fa36651acf592771d09de7937926bb3
cp %{_builddir}/libusb-compat-0.1.7/LICENSE %{buildroot}/usr/share/package-licenses/libusb-compat/9a77bee9a1a48d0c65eaa589a16807f204af2dfe
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/libusb-config

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/usb.h
/usr/lib64/libusb.so
/usr/lib64/pkgconfig/libusb.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libusb-0.1.so.4
/usr/lib64/libusb-0.1.so.4.4.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libusb-compat/9a77bee9a1a48d0c65eaa589a16807f204af2dfe
/usr/share/package-licenses/libusb-compat/caeb68c46fa36651acf592771d09de7937926bb3
